//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : FileManager
//  @ File Name : FileHelper.java
//  @ Date : 2013/4/11
//  @ Author : 
//
//

package com.lzhupload.upload;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import com.lzhupload.upload.model.FObject;

public interface FileHelper {
	public boolean uploadVerify(HttpServletRequest request,
			HttpServletResponse response, FObject fobject);

	public boolean upload(HttpServletRequest request,
			HttpServletResponse response, FObject fobject);
}
